version: "3.9"
services:
    backend-users:
        image: backend-users
        container_name: backend-users
        build:
            context: ./backend-usuarios/microservice
        ports:
            - "8080:8080"
        expose:
            - 8080
    backend-notes:
        image: backend-notes
        container_name: backend-notes
        build:
            context: ./backend-notes/microservice
        ports:
            - "8081:8081"
    backend-login:
        image: backend-login
        container_name: backend-login
        build:
            context: ./backend-login/microservice
        ports:
            - "8082:8082"
    frontend:
        image: frontend
        container_name: frontend  
        build:
            context: ./frontend
        ports:
            - "4200:4200"
        depends_on:
            - backend-users 
            - backend-login
            - backend-notes

