version: "3.9"
services:
    backend:
        image: backend
        container_name: backend
        build:
            context: ./backend/microservice
        ports:
            - "8080:80"
    frontend:
        image: frontend
        container_name: frontend  
        build:
            context: ./frontend
        ports:
            - "4200:80"
        depends_on:
            - backend 
