version: "3.9"
services:
    backend:
        image: demo
        container_name: demo
        build:
            context: ./backend/microservice
        ports:
            - "8080:80"
    frontend:
        image: demo-ui
        container_name: demo-ui
        build:
            context: ./frontend
        ports:
            - "4200:81"
        depends_on:
            - backend 
