apiVersion: apps/v1 # Kubernetes API version
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: angular-deployment
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: backend
        image: docker.io/javirmm/backend:latest # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # The port that the container is running on in the cluster
      - name: frontend
        image:   docker.io/javirmm/frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---

kind: Service  # Kubernetes API version
apiVersion: v1 # Kubernetes resource kind we are creating
metadata:
  name: backend
spec:
  selector:
    app: angular
  ports:
  - protocol: TCP
    port: 8080   # The port that the service is running on in the cluster
    targetPort: 8080   # The port exposed by the service
---

kind: Service  # Kubernetes API version
apiVersion: v1 # Kubernetes resource kind we are creating
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: angular
  ports:
  - protocol: TCP
    port: 80   # The port that the service is running on in the cluster
    targetPort: 4200   # The port exposed by the service
    nodePort: 31000